
# PostgreSQL Database Configuration
# Change database name, username, and password based on your pgAdmin/PostgreSQL setup.
spring.datasource.url=jdbc:postgresql://localhost:5432/Servicerequestmanagement
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# MongoDB Database Configuration
spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.hoydnnp.mongodb.net/SRM?appName=Cluster0
spring.data.mongodb.client.uri=mongodb+srv://admin:admin123@cluster0.hoydnnp.mongodb.net/SRM?appName=Cluster0
spring.data.mongodb.database=SRM

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Server Port
server.port=8007

# JWT Secret
jwt.secret=srmSecretKey123456789SrmPortalJwtSigningKey
jwt.expiration=86400000

# App Name
spring.application.name=srm-backend

# Logging Configuration
debug=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.root=INFO
